name: recipes
description: Recipe Finder

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 
  cached_network_image: 
  flutter_slidable: 
  flutter_svg: 
  shared_preferences: 
  json_annotation: ^3.1.1
  chopper: 
  logging: 
  provider: 
  equatable: 
  sqflite: 
  path_provider: 
  synchronized: 
  sqlbrite: 
  moor_flutter: 



dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.0
  json_serializable: ^3.5.1
  chopper_generator: 
  moor_generator: 

flutter:

  uses-material-design: true

  assets:
    - assets/recipes1.json
    - assets/recipes2.json
    - assets/images/
